"""Core LTBA model types and simple invariants.

This module keeps a compact, well-documented in-memory representation used by
the prototype. It is intentionally small and explicit so reviewers can inspect
semantics without running generation scripts.

Invariants (informal):
- `Guard` is an atomic, opaque label identifying a Boolean condition.
- `LocalBranch` pairs a `Guard` with an algebraic `value` and an optional `tag`.
- `LTBAExpr` stores a base algebraic `base` string plus a flat list of local
  branches attached to that algebraic term. Local branches are not expanded
  into a global product until materialized by explicit conversion.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Dict, Iterable, List, Tuple


@dataclass(frozen=True)
class Guard:
    """Atomic guard label.

    Guards are treated as opaque identifiers for provenance and grouping. They
    are not evaluated by this prototype; satisfiability and arithmetic
    semantics are out of scope.
    """
    text: str

    def __str__(self) -> str:  # pragma: no cover - trivial
        return self.text


@dataclass(frozen=True)
class LocalBranch:
    """A single local branch record attached to an algebraic factor.

    Attributes:
    - guard: Guard labeling the condition for this branch.
    - value: string representing the algebraic payload for this branch.
    - tag: optional short provenance tag used by components.
    """
    guard: Guard
    value: str
    tag: str = ""


@dataclass(frozen=True)
class LocalBranchGroup:
    """A group of alternative local branches generated by one operation.

    Branches in the same group are alternatives; different groups are
    independent unless guard analysis proves otherwise.
    """
    group_id: str
    branches: Tuple[LocalBranch, ...]
    description: str = ""


@dataclass
class LTBAExpr:
    """A minimal LTBA expression.

    The prototype stores `base` (human-readable algebraic text) and a tuple
    of `LocalBranchGroup` records. Materialization computes the Cartesian
    product across groups.
    """
    base: str
    branch_groups: Tuple[LocalBranchGroup, ...] = field(default_factory=tuple)
    provenance: List[str] = field(default_factory=list)

    def add_branch_group(self, group_id: str, branches: List[LocalBranch], description: str = "") -> "LTBAExpr":
        """Return an LTBAExpr with an added LocalBranchGroup (mutating copy)."""
        new_groups = list(self.branch_groups)
        new_groups.append(LocalBranchGroup(group_id=group_id, branches=tuple(branches), description=description))
        return LTBAExpr(self.base, tuple(new_groups), list(self.provenance))

    def add_branch(self, guard: str, value: str, tag: str = "") -> "LTBAExpr":
        """Compatibility helper: add a single-branch group (not typical).

        For reviewers: prefer `add_branch_group` to make grouping explicit.
        """
        lb = LocalBranch(Guard(guard), value, tag)
        return self.add_branch_group(group_id=f"g{len(self.branch_groups)}", branches=[lb])

    @property
    def guard_count(self) -> int:
        guards = {b.guard for g in self.branch_groups for b in g.branches}
        return len(guards)

    @property
    def local_branch_count(self) -> int:
        return sum(len(g.branches) for g in self.branch_groups)

    @property
    def explicit_branch_upper_bound(self) -> int:
        out = 1
        for g in self.branch_groups:
            out *= max(1, len(g.branches))
        return out

    @property
    def representation_size(self) -> int:
        return len(self.base) + sum(len(str(b.guard)) + len(b.value) + len(b.tag) for g in self.branch_groups for b in g.branches)

    def rewrite_local(self, group_index: int, new_value: str, reason: str) -> "LTBAExpr":
        """Return a new LTBAExpr with the first branch in the specified group changed.

        `group_index` indexes into `branch_groups`. We replace the value of the
        first branch in that group to model a local rewrite touching that
        group's records.
        """
        if group_index < 0 or group_index >= len(self.branch_groups):
            raise IndexError("branch group index out of range")
        new_groups = list(self.branch_groups)
        group = new_groups[group_index]
        if not group.branches:
            return LTBAExpr(self.base, tuple(new_groups), list(self.provenance))
        first = group.branches[0]
        new_first = LocalBranch(first.guard, new_value, first.tag)
        new_branches = (new_first,) + tuple(group.branches[1:])
        new_groups[group_index] = LocalBranchGroup(group_id=group.group_id, branches=new_branches, description=group.description)
        new = LTBAExpr(self.base, tuple(new_groups), list(self.provenance))
        new.provenance.append(f"local_rewrite_group:{group_index}:{reason}")
        return new

    def metric_row(self, family: str, n: int, backend: str = "ltba") -> Dict[str, object]:
        return {
            "family": family,
            "n": n,
            "backend": backend,
            "repr_size": self.representation_size,
            "guard_count": self.guard_count,
            "local_branch_count": self.local_branch_count,
            "explicit_branch_upper_bound": self.explicit_branch_upper_bound,
            "provenance_len": len(self.provenance),
        }


@dataclass(frozen=True)
class LTBAComponent:
    """Named component producing LTBAExpr instances for benchmarks/examples."""

    name: str
    layer: str
    description: str
    make_family: Callable[[int], LTBAExpr]


class ComponentRegistry:
    """Simple registry for demo components.

    This is intentionally minimal; reviewers can inspect what families exist
    and how they are constructed.
    """

    def __init__(self) -> None:
        self._items: Dict[str, LTBAComponent] = {}

    def register(self, component: LTBAComponent) -> None:
        self._items[component.name] = component

    def get(self, name: str) -> LTBAComponent:
        return self._items[name]

    def names(self) -> List[str]:
        return sorted(self._items)

    def values(self) -> Iterable[LTBAComponent]:
        return [self._items[k] for k in self.names()]


registry = ComponentRegistry()
